# probes/dna_probes.py
"""
Single-sequence probes for the forward pass.
Yu et al. (2024) only requires one probe — a single forward pass is enough to locate
super weights. Multiple probes are used only to verify position-invariance afterward.

All sequences are real coding sequences, divisible by 6 bp to satisfy
GENERator's 6-mer tokenizer.  Lengths chosen to give stable perplexity estimates:
  actb_500       -> 504 bp  = 84 tokens   (detection + quick ablation, eukaryote)
  actb_full      -> 1128 bp = 188 tokens  (destruction test / ablation, eukaryote)
  pseudomonadota -> 1056 bp = 176 tokens  (destruction test / ablation, prokaryote)
    phage          -> 2178 bp = 363 tokens  (destruction test / ablation, phage)
"""

# Human ACTB (beta-actin) coding sequence - 1128 bp, well-conserved, present in
# every eukaryote training corpus.  Source: NCBI NM_001101.5 CDS.
_ACTB_CDS = (
    "ATGGATGATGATATCGCCGCGCTCGTCGTCGACAACGGCTCCGGCATGTGCAAAGCCGGCTTCGCGGGCGACGATGCCCCGAGGGCC"
    "GTCTTCCCCTCCATCGTGGGGCGCCCCAGGCACCAGGGCGTGATGGTGGGCATGGGTCAGAAGGATTCCTATGTGGGCGACGAGGCC"
    "CAGAGCAAGAGAGGCATCCTCACCCTGAAGTACCCCATCGAGCACGGCATCGTCACCAACTGGGACGACATGGAGAAAATCTGGCAC"
    "CACACCTTCTACAATGAGCTGCGTGTGGCTCCCGAGGAGCACCCCGTGCTGCTCACCGAGGCCCCCCTGAACCCGAAGGCCAACCGC"
    "GAGAAGATGACCCAGATCATGTTTGAGACCTTCAATACCCCCGCCATGTACGTTGCTATCCAGGCTGTGCTATCCCTGTACGCCTCT"
    "GGCCGTACCACTGGCATCGTGATGGACTCCGGTGACGGGGTCACCCACACTGTGCCCATCTACGAGGGGTATGCCCTCCCCCATGCC"
    "ATCCTGCGTCTGGACCTGGCTGGCCGGGACCTGACTGACTACCTCATGAAGATCCTCACCGAGCGCGGCTACAGCTTCACCACCACG"
    "GCCGAGCGGGAAATCGTGCGTGACATTAAGGAGAAGCTGTGCTACGTCGCCCTGGACTTCGAGCAAGAGATGGCCACGGCTGCTTCC"
    "AGCTCCTCCCTGGAGAAGAGCTACGAGCTGCCTGACGGCCAGGTCATCACCATTGGCAATGAGCGGTTCCGCTGCCCTGAGGCACTC"
    "TTCCAGCCTTCCTTCCTGGGCATGGAGTCCTGTGGCATCCACGAAACTACCTTCAACTCCATCATGAAGTGTGACGTGGACATCCGC"
    "AAAGACCTGTACGCCAACACAGTGCTGTCTGGCGGCACCACCATGTACCCTGGCATTGCCGACAGGATGCAGAAGGAGATCACTGCC"
    "CTGGCACCCAGCACAATGAAGATCAAGATCATTGCTCCTCCTGAGCGCAAGTACTCCGTGTGGATCGGCGGCTCCATCCTGGCCTCG"
    "CTGTCCACCTTCCAGCAGATGTGGATCAGCAAGCAGGAGTATGACGAGTCCGGCCCCTCCATCGTCCACCGCAAATGCTTCTAA"
)
assert len(_ACTB_CDS) % 6 == 0, f"ACTB_CDS length {len(_ACTB_CDS)} is not divisible by 6"

# Pseudomonadota genomic probe - NC_002947.4 (Pseudomonas putida KT2440)
# Region 5070808-5071866, trimmed to 1056 bp (nearest multiple of 6). No tandem repeats.
# 1056 % 6 == 0
_PSEUDOMONADOTA = (
    "CGTTGAAGTCAAAGCCTACGATGTCCGCGCAGACACCACTGCCATTCGAGACTGCCGTGATCTTGTTTTTGGTCAGCATGTTCCTGT"
    "TCCTCACCAGCTGAAGGTTACGATCTGTGCCTAACCTACAGCGGCATTCAACTCGACTTCCAATAACAATCAACGAGCATTAATAGC"
    "CTTAGATTATCAATCGGCCAGTTGACCCCAACGCAAGCGTTTGAGCTAAAGCGGGGAGAGACAGGCGCCTACTCATCCATTAATCTG"
    "ATCAATCCATTTGACATCCATGGCTCACCCCTATAAATCAAGACAGCTAAACGGGAGCATCCGATGGATCTACGCCAGATCAAGACAT"
    "TCGTAGTCGTTGCAGAAGAACTGCATTTTGGCCGTGCCGCTGCCCGACTGCAGATCGCCCAACCTGCGGTAACGGCTCAGATTCAAG"
    "CGCTTGAGAGGCAGCTCGGCGTTCCGCTACTGATACGGTCAACCCGCCGTGTGCAGCTCACAGAGGCCGGGATGATCTTCAATTCAC"
    "GGTGTATCGACATCCTTCGGGACATCGACCGCACGTGCCTTGCTACCCAGGCGGTCGCAGGTAAAGACCTCCATCAGATCACTATCG"
    "GTACCATTTACCCCGCGACGTTCGGTGTGCTCCCCAATTTCGTCTCGAGAATCAATCAACGCTTCCCTGAGGCTCGGATCCATATTC"
    "ATAACGGGAACACAGTAGGTATCGTGAGGGAAATTGAGCGCGGCAACATCAATCTCGGTTTCATTCGTCCCGTTGAAAACATCGGCTC"
    "TCTTCGCTGGCAGTCAATCCATCGCGAGAAATATCTGCTAGCGATCGCACGCGAAAACCCTTTGAGCAGCAAGAGCACCGTCACACCT"
    "GACGATTTGCGAAAGCAGAAAATAATCGCGTTCTCTAGGGCATATAATTCTCAGACAGATGACAACTTTCCCGAAGAGTTCAAGAAAT"
    "ACGACCTAAACCAACAGGTTGTTTATAGCTGTAATGATACTCAAGCGATGCTGGCAATGATAACGGCTGGGATTGGGGTGGG"
)
# Trim to exact multiple of 6
_PSEUDOMONADOTA = _PSEUDOMONADOTA.replace("\n", "")
_PSEUDOMONADOTA = _PSEUDOMONADOTA[: (len(_PSEUDOMONADOTA) // 6) * 6]
assert len(_PSEUDOMONADOTA) % 6 == 0

# Phage genomic probe - T4 phage rIIA CDS from /work/11034/atzanakak/t4_rIIA.fasta
# 2178 % 6 == 0
_PHAGE = (
    "ATGATTATCACCACTGAAAAAGAAACAATTCTTGGTAATGGTTCTAAATCAAAAGCATTTAGCATCACAGCATCTCCTAAAGTATTTAAAATTCTGTCATCTGAT"
    "TTGTATACAAACAAGATTCGCGCAGTAGTCCGTGAATTGATTACTAACATGATTGATGCTCATGCACTTAATGGAAATCCTGAAAAATTTATCATACAAGTTCCT"
    "GGACGTTTAGACCCACGATTTGTTTGTCGAGATTTTGGTCCGGGTATGAGTGATTTTGATATTCAAGGTGATGATAATTCTCCTGGGTTGTATAATTCATACTTC"
    "AGTTCATCTAAAGCTGAATCTAATGACTTTATTGGCGGATTTGGTTTAGGTTCTAAATCTCCGTTTAGTTATACTGATACGTTTAGTATTACTTCGTATCATAAA"
    "GGTGAAATTCGTGGTTATGTAGCTTACATGGATGGTGATGGTCCACAGATTAAACCTACATTCGTAAAAGAAATGGGTCCAGATGATAAAACTGGTATTGAAATC"
    "GTAGTTCCAGTTGAAGAAAAAGACTTTAGAAACTTTGCTTATGAAGTTTCTTATATCATGCGACCGTTCAAAGATTTGGCTATCATTAATGGTCTTGACCGCGAA"
    "ATTGATTATTTTCCGGATTTTGATGACTATTACGGTGTAAATCCAGAAAGATACTGGCCTGATCGTGGTGGATTATATGCTATCTACGGTGGTATTGTTTATCCT"
    "ATCGATGGTGTTATTAGAGACCGTAACTGGCTAAGCATTCGCAATGAAGTGAATTACATTAAGTTTCCAATGGGTTCACTTGATATTGCTCCATCTCGCGAGGCT"
    "CTTTCACTGGATGATCGCACTCGTAAAAATATTATTGAACGAGTTAAAGAACTCAGTGAGAAAGCATTTAATGAAGATGTAAAACGATTTAAAGAATCTACATCT"
    "CCTCGTCACACATATCGTGAATTGATGAAGATGGGGTATTCTGCTCGAGATTATATGATTAGTAATTCAGTCAAATTCACGACTAAAAATCTGTCATATAAAAAG"
    "ATGCAGAGCATGTTTGAACCTGACAGTAAGTTATGCAACGCGGGAGTTGTGTATGAAGTAAATCTTGACCCTCGACTGAAGCGCATTAAGCAAAGTCATGAAACT"
    "TCAGCCGTTGCATCAAGTTATCGTCTGTTTGGTATTAATACAACAAAAATTAATATCGTTATTGATAATATTAAAAATCGTGTTAATATTGTCCGTGGATTAGCA"
    "CGTGCGTTAGATGATAGTGAATTTAATAACACTTTGAATATTCATCATAACGAACGTCTTCTGTTTATTAATCCAGAAGTAGAATCGCAGATTGATTTGCTTCCT"
    "GATATTATGGCGATGTTTGAAAGTGATGAAGTTAACATTCATTATTTGTCAGAAATTGAAGCTTTAGTAAAAAGTTATATTCCAAAGGTAGTTAAAAGTAAAGCT"
    "CCTCGTCCTAAAGCTGCTACAGCGTTTAAGTTTGAAATTAAAGACGGGCGCTGGGAAAAGAGGAATTATTTACGCCTCACATCAGAAGCAGATGAAATTACTGGT"
    "TATGTAGCGTATATGCATCGTTCTGATATTTTCTCTATGGATGGTACTACATCTCTTTGTCATCCATCTATGAATATTTTGATTCGTATGGCTAATCTTATTGGC"
    "ATTAATGAATTTTATGTTATTCGTCCGCTTTTACAGAAAAAGGTAAAAGAACTCGGTCAGTGCCAATGTATTTTTGAAGCTTTGCGTGATTTATATGTAGATGCT"
    "TTTGATGATGTAGATTATGATAAGTATGTAGGTTATTCAAGTTCAGCTAAACGATATATTGATAAAATTATCAAGTATCCTGAGTTAGATTTTATGATGAAGTAC"
    "TTCAGTATAGATGAAGTTTCTGAAGAATATACACGACTCGCTAATATGGTTAGTTCATTACAGGGTGTATATTTTAATGGTGGAAAAGATACCATCGGTCATGAC"
    "ATTTGGACAGTAACTAATCTTTTTGATGTATTATCAAATAATGCTTCAAAAAACAGTGATAAAATGGTTGCTGAGTTTACCAAGAAATTCCGTATTGTTTCCGAC"
    "TTCATCGGTTATCGCAACTCTTTAAGTGATGATGAAGTTTCCCAAATCGCTAAAACTATGAAGGCCCTTGCGGCCTAA"
)
assert len(_PHAGE) % 6 == 0

PROBES = {
    # 504 bp = 84 tokens - default for detection and quick sanity checks (eukaryote)
    "actb_500":          _ACTB_CDS[:504],
    # Full 1128 bp = 188 tokens - use for destruction tests / ablation (eukaryote)
    "actb_full":         _ACTB_CDS,
    # Legacy names kept for back-compat, now backed by real sequence
    "human_promoter":    _ACTB_CDS[:504],
    "atg_context":       _ACTB_CDS[:504],
    # Prokaryote probe - 1056 bp from NC_002947.4 (Pseudomonas putida KT2440)
    "pseudomonadota":    _PSEUDOMONADOTA,
    # Phage probe - 2178 bp from T4 phage rIIA CDS
    "phage":             _PHAGE,
    # Poly-A retained as a sanity-check outlier (expect high perplexity)
    "poly_a":            "A" * 504,
}

DEFAULT_PROBE = PROBES["actb_500"]


def get_probe(name: str = "actb_500") -> str:
    if name not in PROBES:
        raise ValueError(f"Unknown probe '{name}'. Available: {list(PROBES.keys())}")
    return PROBES[name]
