"""
scripts/analysis/build_fig2_generator_panels.py
-------------------------------------------------
T0.1 — Consolidate GENERator EUK/PROK activation-lifecycle + ||U_k||_F
mechanistic data into the Fig 2 A-D deliverable schema.

Inputs (already generated by run_activation_lifecycle.py / run_sw_mechanistic.py):
  results/activation_lifecycle_generator.json
  results/activation_lifecycle_generator_prokaryote.json
  results/sw_mechanistic_generator.json
  results/sw_mechanistic_generator_prokaryote.json
  results/super_weight_index.json

Output:
  results/mechanism/fig2_generator_lifecycle_euk.json
  results/mechanism/fig2_generator_lifecycle_prok.json

Each file merges the per-layer activation lifecycle (panel A/B) with the
per-layer ||U_k||_F rank of the frozen SW row(s) at the step-up layer
(panel C/D), plus a `flags` list for any decision-rule violations
(SW row not rank-1 at its step-up layer per T0.1's rule).
"""
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "results"
OUT = RES / "mechanism"
OUT.mkdir(parents=True, exist_ok=True)

CASES = [
    ("generator", "euk"),
    ("generator_prokaryote", "prok"),
]

sw_index = json.loads((RES / "super_weight_index.json").read_text())

for model_key, tag in CASES:
    lifecycle = json.loads((RES / f"activation_lifecycle_{model_key}.json").read_text())
    mech = json.loads((RES / f"sw_mechanistic_{model_key}.json").read_text())

    frob = np.array(mech["frob_norm_uk"])
    d_model = len(frob)
    sw_rows = mech["sw_rows"]
    sw_layer = mech["sw_layer"]

    ranks = {}
    for r in sw_rows:
        rank = int((frob > frob[r]).sum()) + 1  # 1 = highest
        ranks[str(r)] = {
            "frob_norm_uk": float(frob[r]),
            "rank": rank,
            "d_model": d_model,
            "percentile": round(100.0 * (1 - (rank - 1) / d_model), 2),
        }

    flags = []
    for r, info in ranks.items():
        if info["rank"] != 1:
            flags.append(
                f"SW row {r} at layer {sw_layer} is NOT rank-1 in ||U_k||_F "
                f"(rank {info['rank']}/{info['d_model']}, {info['percentile']}th pct) "
                f"-- contradicts the 'SW rows are the top structural amplifier' claim."
            )

    # PROK-specific provenance flag: the frozen index entry for generator_prokaryote
    # was detected with --probe human_promoter (human ACTB, a EUKARYOTE sequence)
    # fed into the PROKARYOTE-specialized model (see run_detection_generator_prokaryote.sbatch).
    # Verified 2026-08-03: none of the 4 canonical probes (human_promoter, pseudomonadota,
    # phage, poly_a) reproduce the recorded out_max=506014 for row 1927 at layer 2 (all
    # give |row1927| < 1.0). A fresh detection sweep with the matching prokaryotic probe
    # (pseudomonadota) does NOT recover row 1927 at all among its top-10 rows; it instead
    # finds a spike at layer 8 (out_max ~30k, rows {260,1325,2789,1408,251,2955,894,1181})
    # and a secondary one at layer 29 (row 2193 -- which independently has the single
    # highest ||U_k||_F, rank 1/3072, among ALL layer-2 output coordinates).
    # This diagnostic re-detection was written only to a scratch path, NOT to
    # results/super_weight_index.json (no re-detection/overwrite performed on canonical data).
    if model_key == "generator_prokaryote":
        flags.append(
            "PROVENANCE: the frozen super_weight_index.json entry for generator_prokaryote "
            "(layer 2, row 1927, out_max=506014) was detected using --probe human_promoter "
            "(human ACTB, a EUKARYOTE sequence) against the PROKARYOTE-specialized model. "
            "None of the 4 canonical probes reproduce that magnitude on row 1927 (all <1.0). "
            "A diagnostic re-detection with the matching pseudomonadota probe does not recover "
            "row 1927 in its top-10 and instead surfaces layer-8 rows and a layer-29 spike at "
            "row 2193 (the weight-space rank-1 ||U_k||_F coordinate at layer 2). "
            "This SW entry is likely a probe-mismatch artifact, not a genuine PROK super weight; "
            "the frozen index was NOT modified -- flagging for collaborator/PI decision."
        )

    out = {
        "model": model_key,
        "sw_layer": sw_layer,
        "sw_rows": sw_rows,
        "n_layers": len(lifecycle["layers"]),
        "n_seqs": lifecycle["n_seqs"],
        "panel_AB_activation_lifecycle": {
            "layers": lifecycle["layers"],
            "mean_post_residual_sw": lifecycle["mean_post_residual_sw"],
            "mean_block_delta_sw": lifecycle["mean_block_delta_sw"],
            "mean_post_residual_top3": lifecycle["mean_post_residual_top3"],
        },
        "panel_CD_uk_bar": {
            "d_model": d_model,
            "frob_norm_uk": mech["frob_norm_uk"],
            "sw_row_ranks": ranks,
        },
        "flags": flags,
        "meta": {
            "source_files": [
                f"results/activation_lifecycle_{model_key}.json",
                f"results/sw_mechanistic_{model_key}.json",
                "results/super_weight_index.json",
            ],
            "precision": "float32",
            "device": "cuda (activation lifecycle) / cpu (weight-only Uk audit)",
        },
    }

    out_path = OUT / f"fig2_generator_lifecycle_{tag}.json"
    out_path.write_text(json.dumps(out, indent=2))
    print(f"[build_fig2] {model_key}: rank(s)={[(r, v['rank']) for r, v in ranks.items()]}  "
          f"flags={len(flags)}  -> {out_path}")
