"""
scripts/analysis/run_dnabert2_residual_attribution.py
-----------------------------------------------------
Resolves the layer-7-row-603 ||U_k||_F outlier (rank 706/768) in the
DNABERT-2 mechanism audit.

Hypothesis: row 603 is generated by the MLP amplifier at layers 3/5/6 and
then carried through layer 7 by the residual stream rather than re-amplified
by layer 7's MLP. The U_k predictor only sees what each layer's MLP would
produce de-novo; a residually-carried channel is invisible to it.

Test: run a single forward pass on the probe sequence and record, for the
DNABERT-2 residual stream coordinate 603 at the SW token position, the
*per-layer contribution* from (a) the layer's MLP output and (b) the
residual carry-in. If layers 3/5/6 are net-contributing and layer 7 is
near-zero or even slightly damping, that confirms the residual-reuse story.

Output
------
results/sw_residual_attribution_dnabert2.json
"""
from __future__ import annotations

import json
from pathlib import Path

import torch
import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
ROW = 603  # the SW row of interest (appears at layers 3, 5, 6, 7)


def main():
    import sys; sys.path.insert(0, str(ROOT))
    from models import WRAPPER_MAP
    from src.dna_probes import get_probe

    config = yaml.safe_load((ROOT / "configs/dnabert2.yaml").read_text())
    wrapper_cls = WRAPPER_MAP["dnabert2"]
    wrapper = wrapper_cls(config)
    wrapper.load()
    model = wrapper.model
    tokenizer = wrapper.tokenizer
    device = next(model.parameters()).device

    seq = get_probe("actb_500")
    inp = tokenizer(seq, return_tensors="pt", truncation=True, max_length=512)
    inp = {k: v.to(device) for k, v in inp.items()}

    # Find the underlying BERT encoder
    bert = model.bert if hasattr(model, "bert") else model
    enc = bert.encoder
    n_layers = len(enc.layer)
    print(f"[residual_attr] n_layers = {n_layers}, target row = {ROW}")

    # We want, per layer:
    #   - residual_in:   the hidden state BEFORE this layer's MLP add
    #   - mlp_out:       the MLP block's output (what gets added)
    #   - residual_out:  residual_in + mlp_out (== layer output)
    #
    # DNABERT-2 BertLayer (custom): forward does
    #       attn_out = self.attention(...)
    #       intermediate = self.mlp(attn_out)             <- gated MLP, then output projection
    #       layer_out = self.mlp.layernorm(intermediate + attn_out)  (if residual)
    #
    # We hook the mlp.wo (down_proj) — its output is what gets added back.
    # The residual-in is `attn_out` (the input to mlp.wo's containing block).
    # Easiest: hook each BertLayer.mlp, capture (input, output).

    records: list[dict] = [{} for _ in range(n_layers)]

    def make_hook(li):
        def hook(module, inputs, output):
            # `inputs[0]` is attn_out (residual carry-in to MLP block)
            # `output` is mlp(attn_out) before residual+LN
            # DNABERT-2 packs batch*length into 2D: (N, H) where N = unpadded tokens.
            attn_out = inputs[0]            # (N, H) or (B, L, H)
            mlp_out  = output                # same shape
            if attn_out.dim() == 3:
                a = attn_out[0]; m = mlp_out[0]
            else:
                a = attn_out; m = mlp_out
            sw_pos = int(a[:, ROW].abs().argmax().item())
            records[li] = {
                "layer":         li,
                "sw_pos":        sw_pos,
                "residual_in":   float(a[sw_pos, ROW].item()),
                "mlp_out":       float(m[sw_pos, ROW].item()),
                "residual_out":  float((a + m)[sw_pos, ROW].item()),
                "mlp_out_max_row": int(m[sw_pos].abs().argmax().item()),
                "mlp_out_max_val": float(m[sw_pos].abs().max().item()),
                "residual_in_abs": float(a[sw_pos, ROW].abs().item()),
                "mlp_out_abs":     float(m[sw_pos, ROW].abs().item()),
            }
        return hook

    handles = []
    for li in range(n_layers):
        layer = enc.layer[li]
        handles.append(layer.mlp.register_forward_hook(make_hook(li)))

    with torch.no_grad():
        model(**inp)

    for h in handles:
        h.remove()

    print(f"{'layer':>5} {'pos':>5} {'residual_in[603]':>18} "
          f"{'mlp_out[603]':>14} {'residual_out[603]':>18} "
          f"{'arg|mlp|':>10} {'max|mlp|':>10}")
    print("-" * 90)
    for r in records:
        print(f"{r['layer']:5d} {r['sw_pos']:5d} "
              f"{r['residual_in']:18.3f} "
              f"{r['mlp_out']:14.3f} "
              f"{r['residual_out']:18.3f} "
              f"{r['mlp_out_max_row']:10d} "
              f"{r['mlp_out_max_val']:10.3f}")

    out = {
        "model":  "dnabert2",
        "probe":  "actb_500",
        "row":    ROW,
        "per_layer": records,
        "note":   ("residual_in   = attn_out at row 603 (entering the MLP block).\n"
                   "mlp_out       = MLP block contribution at row 603 (signed).\n"
                   "If row 603 is residually carried at layer 7, |mlp_out[7,603]| "
                   "<< |residual_in[7,603]| and the U_k predictor (which only "
                   "sees the MLP) is correctly indicating layer 7's MLP is not "
                   "the source.")
    }
    out_path = ROOT / "results/sw_residual_attribution_dnabert2.json"
    out_path.write_text(json.dumps(out, indent=2))
    print(f"\n[residual_attr] wrote {out_path}")


if __name__ == "__main__":
    main()
