# probes/dna_probes.py
"""
Single-sequence probes for the forward pass.
Yu et al. (2024) only requires one probe — a single forward pass is enough to locate
super weights. Multiple probes are used only to verify position-invariance afterward.

All sequences are real eukaryotic coding sequences, divisible by 6 bp to satisfy
GENERator's 6-mer tokenizer.  Lengths chosen to give stable perplexity estimates:
  actb_500  → 504 bp = 84 tokens   (detection + quick ablation)
  actb_full → 1128 bp = 188 tokens (destruction test / ablation)
"""

# Human ACTB (beta-actin) coding sequence — 1128 bp, well-conserved, present in
# every eukaryote training corpus.  Source: NCBI NM_001101.5 CDS.
_ACTB_CDS = (
    "ATGGATGATGATATCGCCGCGCTCGTCGTCGACAACGGCTCCGGCATGTGCAAAGCCGGCTTCGCGGGCGACGATGCCCCGAGGGCC"
    "GTCTTCCCCTCCATCGTGGGGCGCCCCAGGCACCAGGGCGTGATGGTGGGCATGGGTCAGAAGGATTCCTATGTGGGCGACGAGGCC"
    "CAGAGCAAGAGAGGCATCCTCACCCTGAAGTACCCCATCGAGCACGGCATCGTCACCAACTGGGACGACATGGAGAAAATCTGGCAC"
    "CACACCTTCTACAATGAGCTGCGTGTGGCTCCCGAGGAGCACCCCGTGCTGCTCACCGAGGCCCCCCTGAACCCGAAGGCCAACCGC"
    "GAGAAGATGACCCAGATCATGTTTGAGACCTTCAATACCCCCGCCATGTACGTTGCTATCCAGGCTGTGCTATCCCTGTACGCCTCT"
    "GGCCGTACCACTGGCATCGTGATGGACTCCGGTGACGGGGTCACCCACACTGTGCCCATCTACGAGGGGTATGCCCTCCCCCATGCC"
    "ATCCTGCGTCTGGACCTGGCTGGCCGGGACCTGACTGACTACCTCATGAAGATCCTCACCGAGCGCGGCTACAGCTTCACCACCACG"
    "GCCGAGCGGGAAATCGTGCGTGACATTAAGGAGAAGCTGTGCTACGTCGCCCTGGACTTCGAGCAAGAGATGGCCACGGCTGCTTCC"
    "AGCTCCTCCCTGGAGAAGAGCTACGAGCTGCCTGACGGCCAGGTCATCACCATTGGCAATGAGCGGTTCCGCTGCCCTGAGGCACTC"
    "TTCCAGCCTTCCTTCCTGGGCATGGAGTCCTGTGGCATCCACGAAACTACCTTCAACTCCATCATGAAGTGTGACGTGGACATCCGC"
    "AAAGACCTGTACGCCAACACAGTGCTGTCTGGCGGCACCACCATGTACCCTGGCATTGCCGACAGGATGCAGAAGGAGATCACTGCC"
    "CTGGCACCCAGCACAATGAAGATCAAGATCATTGCTCCTCCTGAGCGCAAGTACTCCGTGTGGATCGGCGGCTCCATCCTGGCCTCG"
    "CTGTCCACCTTCCAGCAGATGTGGATCAGCAAGCAGGAGTATGACGAGTCCGGCCCCTCCATCGTCCACCGCAAATGCTTCTAA"
)

# Trim to exact multiples of 6 bp for GENERator's 6-mer tokenizer
# Full: 1128 bp ÷ 6 = 188 tokens  (last codon TAA = stop, total divisible by 6? check below)
# 1128 % 6 == 0 ✓   504 % 6 == 0 ✓
_ACTB_LEN = len(_ACTB_CDS)
assert _ACTB_LEN % 6 == 0, f"ACTB_CDS length {_ACTB_LEN} is not divisible by 6"

PROBES = {
    # 504 bp = 84 tokens — default for detection and quick sanity checks
    "actb_500":       _ACTB_CDS[:504],
    # Full 1128 bp = 188 tokens — use for destruction tests / ablation
    "actb_full":      _ACTB_CDS,
    # Legacy names kept for back-compat, now backed by real sequence
    "human_promoter": _ACTB_CDS[:504],
    "atg_context":    _ACTB_CDS[:504],
    # Poly-A retained as a sanity-check outlier (expect high perplexity)
    "poly_a":         "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
}

DEFAULT_PROBE = PROBES["actb_500"]


def get_probe(name: str = "actb_500") -> str:
    if name not in PROBES:
        raise ValueError(f"Unknown probe '{name}'. Available: {list(PROBES.keys())}")
    return PROBES[name]
